-- Run these in phpMyAdmin
CREATE DATABASE social_credit;
USE social_credit;

CREATE TABLE users (
    UID VARBINARY(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARBINARY(64) NOT NULL,
    credit_score INT DEFAULT 1000,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE debts (
    DID CHAR(36) PRIMARY KEY,
    UID VARBINARY(64),
    Data TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UID) REFERENCES users(UID) ON DELETE CASCADE
);


